server:
  port: 8086
spring:
  rabbitmq:
    host: 47.109.137.60
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123
hm:
  db:
    database: hm-pay
  swagger:
    title: "黑马商城支付服务接口文档"
    desc: "黑马商城支付服务接口文档"
    package: com.hmall.pay.controller

