server:
  port: 8085
spring:
  rabbitmq:
    host: 47.109.137.60
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123
hm:
  db:
    database: hm-trade
  swagger:
    title: "黑马商城交易服务接口文档"
    desc: "黑马商城交易服务接口文档"
    package: com.hmall.trade.controller

