server:
  port: 8082
feign:
  okhttp:
    enabled: true
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true #开启请求方式加前缀
  rabbitmq:
    host: 47.109.137.60
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城购物车服务接口文档"
    desc: "黑马商城购物车服务接口文档"
    package: com.hmall.cart.controller