server:
  port: 8081
spring:
  rabbitmq:
    host: 47.109.137.60
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123
hm:
  db:
    database: hm-item
  swagger:
    title: "黑马商城商品服务接口文档"
    desc: "黑马商城商品服务接口文档"
    package: com.hmall.item.controller

